<a href="https://colab.research.google.com/github/Arayandra/Andraaseventeen/blob/main/Latihan_3_DAA_(13_09_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [154]:
import datetime
Tanggal = datetime.date.today()
Mahasiswa = ["Advani Rayandra Kahfi", "2022071007", "Informatika", "Desain Analisis dan Algoritma", Tanggal.strftime("%d-%m-%y") ,"Universitas Pembangunan Jaya"]

print (Mahasiswa)

['Advani Rayandra Kahfi', '2022071007', 'Informatika', 'Desain Analisis dan Algoritma', '13-09-23', 'Universitas Pembangunan Jaya']


In [155]:
print("NIM : ", Mahasiswa[1])

NIM :  2022071007


In [156]:
print("Nama Universitas : ",Mahasiswa[-1] )

Nama Universitas :  Universitas Pembangunan Jaya


In [157]:
print("NIM dan Prodi : ", Mahasiswa[1:3])
#Untuk print dari indeks yang ditentuin pertama sampai indeks sebelum angka yang ditentukan

NIM dan Prodi :  ['2022071007', 'Informatika']


In [158]:
print("Nama Mahasiswa dan NIM : ", Mahasiswa[0:2])

Nama Mahasiswa dan NIM :  ['Advani Rayandra Kahfi', '2022071007']


In [159]:
for Awikwok_jawir in Mahasiswa:
  print("UPJ " + Awikwok_jawir)

UPJ Advani Rayandra Kahfi
UPJ 2022071007
UPJ Informatika
UPJ Desain Analisis dan Algoritma
UPJ 13-09-23
UPJ Universitas Pembangunan Jaya


In [160]:
bin_Mahasiswa = ["Najib", "Fahmi", "Daffa", "Natan"]

for aMahasiswa in bin_Mahasiswa:
  print(aMahasiswa + " Jawir")

Najib Jawir
Fahmi Jawir
Daffa Jawir
Natan Jawir


In [161]:
for BangJago in Mahasiswa:
  #print("UPJ" + BangJago)
  print(type(BangJago))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [162]:
UPJ = ("Universitas", "Pembangunan", "Jaya")

print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [163]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [164]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[2:]

('Blue', 'Yellow')

In [179]:
hariAwal = ("senin","selasa","rabu")
hariAkhir = ("kamis","jumat","sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [165]:
Pertama = ("100")
Kedua = ("200", "400", "600")
Ketiga = ("300")
Keempat = ("400", "800")

Hitungan = Pertama, Kedua, Ketiga, Keempat
print(Hitungan)



('100', ('200', '400', '600'), '300', ('400', '800'))


In [166]:
bin_colors ={
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"
}
print(bin_colors)


{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [167]:
bin_colors.get('approved_color')
bin_colors['approved_color']


'Green'

In [168]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [169]:
dictMahasiswa = {"Nama" : "Advani Rayandra Kahfi", "NIM" : "2022071007", "Prodi" : "Informatika", "Universitas" : "Universitas Pembangunan Jaya"}

print(dictMahasiswa)

{'Nama': 'Advani Rayandra Kahfi', 'NIM': '2022071007', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


In [170]:
dictMahasiswa = {"Nama" : "Advani Rayandra Kahfi", "NIM" : "2022071007", "Prodi" : "Informatika", "Universitas" : "Universitas Pembangunan Jaya"}

print(dictMahasiswa)
print(dictMahasiswa  ["Nama"])

{'Nama': 'Advani Rayandra Kahfi', 'NIM': '2022071007', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}
Advani Rayandra Kahfi


In [171]:
dictMahasiswa = {"Nama" : "Advani Rayandra Kahfi","Nama" : "Advani Rayandra Kahfi","NIM" : "2022071007", "Prodi" : "Informatika", "Universitas" : "Universitas Pembangunan Jaya","Universitas" : "Universitas Pembangunan Jaya"}

print(dictMahasiswa)

{'Nama': 'Advani Rayandra Kahfi', 'NIM': '2022071007', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


In [172]:
#Inisiasi Set
set_01 = {4,5,6,2}
print(set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)

#Menghapus set
set_01.discard(5)
print(set_01)

#Menambah set
set_04 = {2,3,4,5,6}
set_04.add(1)
print(set_04)

#set yang sudah dihapus tidak akan muncul walaupun sudah ditambahkan dengan angka yg lain
set_01.add(1)
print(set_01)




{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}
{2, 4, 6}
{1, 2, 3, 4, 5, 6}
{1, 2, 4, 6}


In [173]:
set_04= {1, 2, 3, 4, 5, 6, 7, 8}
set_04.discard(4)#hapus nilai 4
print(set_04)

set_04.add(10) #menambahkan nilai 10
print(set_04)


{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


In [174]:
#Union set
set_A = {1,2,3,4}
set_B = {3,4,5,6}
#Cara 1
print(set_A|set_B)
#Cara 2
print(set_A.union(set_B))

#Intersection (Irisan)
#Cara 1
print(set_A & set_B)
#Cara 2
print(set_A.intersection(set_B))

#Difference set
#A - B
#Cara 1
print(set_A - set_B)
#Cara 2
print(set_A.difference(set_B))

#B - A
#Cara 1
print(set_B - set_A)
#Cara 2
print(set_B.difference(set_A))

#Symmetric Difference
#Cara 1
print(set_A ^ set_B)
#Cara 2
print(set_A.symmetric_difference(set_B))



{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{3, 4}
{3, 4}
{1, 2}
{1, 2}
{5, 6}
{5, 6}
{1, 2, 5, 6}
{1, 2, 5, 6}


In [175]:
#Menyusun red dan green
Red = {"dandelions", "fire hydrant", "leaves"}
Green = {"leaves","fire hydrant", "rose", "blood"}

print(Green|Red)
print(Green&Red)

{'rose', 'blood', 'dandelions', 'leaves', 'fire hydrant'}
{'leaves', 'fire hydrant'}


In [176]:
#Buat database
import pandas as pd

data = {'satu': [1,1,1,1,1],
        'dua' : [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}

df = pd.DataFrame(data, index=['a','b','c','d','e'])

df.head()


satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [177]:
#Buat database mahasiswa
df = pd.DataFrame([[1, "Informatika", 50,30,20],
        [2, "Sistem Informasi", 55,30,25],
        [3, "Teknik Sipil", 40,30,10]])

df.columns = ["No", "Prodi", "Mahasiswa", "Laki-laki", "Perempuan"]

df.style.hide(axis='index')

In [178]:
import numpy as np

matrix = np.array([
    [100,200,300],
    [700,600,500],
    [900,1000,800]
])

print(matrix)

print("\ntranspose: ")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

transpose: 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
